#修改SpringBoot的端口
server:
  port: 8055
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
    password: wenhao

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lm_cloud_admin
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource #简单引入druid
    tdengine:
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      url: jdbc:TAOS-RS://127.0.0.1:6041/lm_cloud_data
      username: root
      password: taosdata



# tcp 自定义的参数
netty:
  server:
    host: 127.0.0.1
    port: 20000
